# Try to find the muParser library
#  MUPARSER_FOUND - system has muParser lib
#  MUPARSER_INCLUDE_DIRS - the include directories needed
#  MUPARSER_LIBRARIES - libraries needed

FIND_PATH(MUPARSER_INCLUDE_DIR NAMES muParser.h)
FIND_LIBRARY(MUPARSER_LIBRARY NAMES muparser)

SET(MUPARSER_INCLUDE_DIRS ${MUPARSER_INCLUDE_DIR})
SET(MUPARSER_LIBRARIES ${MUPARSER_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MUPARSER DEFAULT_MSG MUPARSER_LIBRARY MUPARSER_INCLUDE_DIR)

MARK_AS_ADVANCED(MUPARSER_INCLUDE_DIR MUPARSER_LIBRARY)
