# Try to find the QScintilla2 library
#  QSCINTILLA_FOUND - system has QSCINTILLA lib
#  QScintilla_INCLUDE_DIRS - the include directories needed
#  QScintilla_LIBRARIES - libraries needed

FIND_PATH(QSCINTILLA_INCLUDE_DIR NAMES Qsci/qsciscintilla.h PATH_SUFFIXES qt5)
FIND_LIBRARY(QSCINTILLA_LIBRARY NAMES qsciscintilla qt5scintilla2)

SET(QScintilla_INCLUDE_DIRS ${QSCINTILLA_INCLUDE_DIR})
SET(QScintilla_LIBRARIES ${QSCINTILLA_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QScintilla DEFAULT_MSG QSCINTILLA_LIBRARY QSCINTILLA_INCLUDE_DIR)

MARK_AS_ADVANCED(QSCINTILLA_INCLUDE_DIR QSCINTILLA_LIBRARY)
