# Try to find the Voro++ library
#  VOROPLUSPLUS_FOUND - system has muParser lib
#  VOROPLUSPLUS_INCLUDE_DIRS - the include directories needed
#  VOROPLUSPLUS_LIBRARIES - libraries needed

FIND_PATH(VOROPLUSPLUS_INCLUDE_DIR NAMES voro++.hh)
FIND_LIBRARY(VOROPLUSPLUS_LIBRARY NAMES voro++)

SET(VOROPLUSPLUS_INCLUDE_DIRS ${VOROPLUSPLUS_INCLUDE_DIR})
SET(VOROPLUSPLUS_LIBRARIES ${VOROPLUSPLUS_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VOROPLUSPLUS DEFAULT_MSG VOROPLUSPLUS_LIBRARY VOROPLUSPLUS_INCLUDE_DIR)

MARK_AS_ADVANCED(VOROPLUSPLUS_INCLUDE_DIR VOROPLUSPLUS_LIBRARY)
