# Try to find the QScintilla2 library
#  QSCINTILLA_FOUND - system has QSCINTILLA lib
#  QSCINTILLA_INCLUDE_DIRS - the include directories needed
#  QSCINTILLA_LIBRARIES - libraries needed

FIND_PATH(QSCINTILLA_INCLUDE_DIR NAMES QSci/qsciscintilla.h)
FIND_LIBRARY(QSCINTILLA_LIBRARY NAMES qsciscintilla)

SET(QSCINTILLA_INCLUDE_DIRS ${QSCINTILLA_INCLUDE_DIR})
SET(QSCINTILLA_LIBRARIES ${QSCINTILLA_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QSCINTILLA DEFAULT_MSG QSCINTILLA_LIBRARY QSCINTILLA_INCLUDE_DIR)

MARK_AS_ADVANCED(QSCINTILLA_INCLUDE_DIR QSCINTILLA_LIBRARY)
