
# This helper file provides information on the program version of OVITO. 

SET(OVITO_VERSION_MAJOR 		"2")
SET(OVITO_VERSION_MINOR 		"0")
SET(OVITO_VERSION_REVISION		"0")
SET(OVITO_FILE_FORMAT_VERSION	"100")

# Make the version information available to the source code.

ADD_DEFINITIONS("-DOVITO_VERSION_MAJOR=${OVITO_VERSION_MAJOR}")
ADD_DEFINITIONS("-DOVITO_VERSION_MINOR=${OVITO_VERSION_MINOR}")
ADD_DEFINITIONS("-DOVITO_VERSION_REVISION=${OVITO_VERSION_REVISION}")
ADD_DEFINITIONS("-DOVITO_FILE_FORMAT_VERSION=${OVITO_FILE_FORMAT_VERSION}")
